### ISSUE TITLE
website is not live

### ISSUE THREAD

**Issue by jainamthakkar** [shashirajraja/Train-Ticket-Reservation-System#6]
![Screenshot (432)](https://user-images.githubusercontent.com/105544028/229422886-4b5562c7-ce5d-4e51-aadf-f92fda0fc306.png)

**Comment by shashirajraja** [comment]
The free hosting benefit provided by Heroku has been expired, so its not live anymore.

**Comment by jainamthakkar** [comment]
@shashirajraja okay!!
can you suggest me some Repository or projects where i can contribute with JAVA ?

**Comment by Lokesh-Manola** [comment]
I am new in github can you  suggest me how to get my first contribution

**Comment by Lokesh-Manola** [comment]
Thanks, I'll check it out.

**Comment by shashirajraja** [comment]
Hi @jainamthakkar @Lokesh-Manola , if you wanted to contribute in some Java Projects you can use the projects available in my repository: https://github.com/shashirajraja?tab=repositories&q=&type=&language=java

If you think any additional functionality should be available to those projects, you can raise an issue, get it assigned and start working on that.

There are also many repositories like that available, you can search it on github.

**Comment by jainamthakkar** [comment]
@shashirajraja okay thank you!
